workload:
  name: myapi
replicaCount: 1
labels:
  classification: public
  environment: prod
  team: 20261005-team
service:
  port: 8000
  targetPort: 8000
container:
  port: 8000
resources:
  requests:
    cpu: 500m
    memory: 512Mi
